
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Justin5174110
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp


mybatis:
  mapper-locations: classpath:com/example/community/dao/*Mapper.xml
  type-aliases-package: com.example.demo.domain

#showSql
logging:
  level:
    com:
      example:
        demo:
          mapper : debug